version: "3"

services:
  php:
    build:
      context: .docker/php
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./:/var/www/html
  web:
    image: nginx:1.29
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 81:80
